---
- include: deps.yml
- name: "Restarting RethinkDB"
  service:
    name=rethinkdb 
    state=restarted
- name: "Copying Projects"
  copy: 
    src="{{ item }}"
    dest=/opt/
    mode=u=r,g=r
  with_items: "{{ projects }}"
- name: "Running npm install"
  command: bash -c "npm install --loglevel verbose|| npm install --loglevel verbose"
    chdir="/opt/{{ item }}"
    creates="/opt/{{ item }}/node_modules"
  with_items: "{{ projects }}"
- name: "Installing upstart scripts"
  copy:
    src="upstart/{{ item }}.conf"
    dest=/etc/init/
    mode=u=r,g=r
  with_items: "{{ services }}"  
- name: "Run Shot and Share Services"
  service:
    name={{ item }}
    state=restarted
    enabled=yes
    # init-checkconf /etc/init/{{ item }}.conf  
  with_items: "{{ services }}"
- name: "Copying NGINX config files"
  copy: 
    src="nginx/{{ item }}"
    dest="/etc/nginx/sites-enabled/{{ item }}"
    mode=u=r,g=r,o=r
  with_items:
    - shsh.conf
    - shsh-api.conf
    - shsh-ws.conf
- name: "Restarting NGINX"
  service:
    name=nginx
    state=reloaded